language: node_js
os: linux
sudo: false
dist: trusty
addons:
node_js:
  - '10'
  - '12'
install:
  - yarn bootstrap
before_script:
  - npm run build
script:
  - npm run test ci
after_success:
  - cat coverage/lcov.info | coveralls
